In [3]:
import numpy as np


In [50]:
class Operations:
    def __init__(self, rng):
        self.rng = rng
    def uni_crossover(self, ind1, ind2):

        ind1 = np.array(ind1)
        ind2 = np.array(ind2)
        ind_temp = ind1.copy()
        op = self.rng.choice([False, True], len(ind1))

        for iterator, value in enumerate(op):
            if value:
 
                ind1[iterator]=ind2[iterator]
                ind2[iterator]=ind_temp[iterator]

        return ind1, ind2
    
    def result(self, X, y, e, Xcf, p, model):
        
        
        return diff
    

operations = Operations(np.random.default_rng(883))
operations.uni_crossover([1,0,1,0,1,0,1,0],
                         [1,1,1,1,0,0,0,0])



[1 0 1 0 1 0 1 0] [1 1 1 1 0 0 0 0]
[1 1 1 1 0 0 1 0] [1 0 1 0 1 0 0 0]


(array([1, 1, 1, 1, 0, 0, 1, 0]), array([1, 0, 1, 0, 1, 0, 0, 0]))